version: '3.8'

services:
  # Contenedor 1: Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: reto_final_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: reto_final
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  # Contenedor 2: Aplicaci√≥n Spring Boot
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reto_final_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/reto_final
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
    networks:
      - app-network

  # Contenedor 3: Servidor web NGINX
  nginx:
    image: nginx:alpine
    container_name: reto_final_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local
